Fix format not a string literal and no format arguments error
Compilation with strictness turned on (for the Debian build) was giving
these errors:

    ONEWSENG.cpp: In member function ‘void News::firm_constructed()’:
    ONEWSENG.cpp:1759:17: error: format not a string literal and no format arguments [-Werror=format-security]
     1759 |         snprintf(str, MAX_STR_LEN+1, _(firm_constructed_msg[short_para1-1]));
          |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ONEWSENG.cpp: In member function ‘void News::weapon_ship_built()’:
    ONEWSENG.cpp:1834:25: error: format not a string literal and no format arguments [-Werror=format-security]
     1834 |                 snprintf(str, MAX_STR_LEN+1, weapon_ship_built_msg[short_para1-UNIT_CATAPULT]);
          |                 ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix this by using strncpy instead of snprintf with no format arguments.