Fix DEBUG build
Compilation was failing with errors such as:

    OAI_MAIN.cpp:147:14: error: ‘sys’ was not declared in this scope
    OAI_MAIN.cpp:230:12: error: ‘debug_sim_game_type’ was not declared in this scope

This was due to the overzealous header cleanup done previously excluding
some headers that are used only in the DEBUG build.

Fix this by including the necessary headers only in the DEBUG build.