Really fix out-of-tree builds and "make distcheck"
Commit d636a045 didn't fix everything.

Building in a directory different from the source directory failed with:

    make[3]: Entering directory '<...>/7kaa-2.15.7/_build/sub/src'
    g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../../../src -I../include  -DPACKAGE_DATA_DIR=\"<...>/7kaa-2.15.7/_inst/share/7kaa\" -DLOCALE_DIR=\"<...>/7kaa-2.15.7/_inst/share/locale\"  -include "../include/config.h" -fsigned-char -mfpmath=387 -ffloat-store -D_REENTRANT -I/usr/include/SDL2 -g -O2 -MT AM.o -MD -MP -MF .deps/AM.Tpo -c -o AM.o ../../../src/AM.cpp
    ../../../src/AM.cpp:24:10: fatal error: ALL.h: No such file or directory
       24 | #include <ALL.h>
          |          ^~~~~~~
    compilation terminated.
    make[3]: *** [Makefile:1113: AM.o] Error 1
    make[3]: Leaving directory '<...>/7kaa-2.15.7/_build/sub/src'

With the "-I$(top_srcdir)/include" flag, now make runs the following
successful command:

    make[3]: Entering directory '<...>/7kaa-2.15.7/_build/sub/src'
    g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../../../src -I../include  -I../../../include -DPACKAGE_DATA_DIR=\"<...>/7kaa-2.15.7/_inst/share/7kaa\" -DLOCALE_DIR=\"<...>/7kaa-2.15.7/_inst/share/locale\"  -include "../include/config.h" -fsigned-char -mfpmath=387 -ffloat-store -D_REENTRANT -I/usr/include/SDL2 -g -O2 -MT AM.o -MD -MP -MF .deps/AM.Tpo -c -o AM.o ../../../src/AM.cpp
    mv -f .deps/AM.Tpo .deps/AM.Po