Fix out-of-tree builds and "make distcheck"
Building in a directory different from the source directory failed
immediately with:

    make[3]: Entering directory '<...>/7kaa-2.15.7/_build/sub/src/enet'
    g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../../../../src/enet -I../../include    -include "../../include/config.h" -fsigned-char -mfpmath=387 -ffloat-store  -g -O2 -MT multiplayer.o -MD -MP -MF .deps/multiplayer.Tpo -c -o multiplayer.o ../../../../src/enet/multiplayer.cpp
    ../../../../src/enet/multiplayer.cpp:25:10: fatal error: multiplayer.h: No such file or directory
       25 | #include <multiplayer.h>
          |          ^~~~~~~~~~~~~~~
    compilation terminated.
    make[3]: *** [Makefile:379: multiplayer.o] Error 1
    make[3]: Leaving directory '<...>/7kaa-2.15.7/_build/sub/src/enet'

With "-I$(top_srcdir)/include" flags, now make runs the following
successful command:

    make[3]: Entering directory '<...>/7kaa-2.15.7/_build/sub/src/enet'
    g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../../../../src/enet -I../../include  -I../../../../include  -include "../../include/config.h" -fsigned-char -mfpmath=387 -ffloat-store  -g -O2 -MT multiplayer.o -MD -MP -MF .deps/multiplayer.Tpo -c -o multiplayer.o ../../../../src/enet/multiplayer.cpp
    mv -f .deps/multiplayer.Tpo .deps/multiplayer.Po
    rm -f libmultiplayer.a
    ar cru libmultiplayer.a multiplayer.o
    ar: `u' modifier ignored since `D' is the default (see `U')
    ranlib libmultiplayer.a
    make[3]: Leaving directory '<...>/7kaa-2.15.7/_build/sub/src/enet'