Fix OREGION.h build error in DEBUG
Compilation was failing with:

    OREGION.cpp:246:46: error: invalid use of incomplete type ‘class RegionStat’

This was due to a required header (OREGIONS.h) being excluded from
OREGION.h in the DEBUG build.  It is unclear why this was done.